seed:
  enabled: true
  slices:
    - sst: 1
      sd: "000001"
      default_indicator: true
      session:
        - name: internet
          type: 1
          pcc_rule: []
          ambr:
            uplink: {value: 1, unit: 3}
            downlink: {value: 1, unit: 3}
          qos:
            index: 9
            arp: {priority_level: 8, pre_emption_capability: 1, pre_emption_vulnerability: 1}
    - sst: 2
      sd: "000002"
      default_indicator: true
      session:
        - name: streaming
          type: 1
          pcc_rule: []
          ambr:
            uplink: {value: 1, unit: 3}
            downlink: {value: 1, unit: 3}
          qos:
            index: 9
            arp: {priority_level: 8, pre_emption_capability: 1, pre_emption_vulnerability: 1}
  subscribers:
    - imsi: "001010000000001"
      key: "465B5CE8B199B49FAA5F0A2EE238A6BC"
      opc: "E8ED289DEBA952E4283B54E88E6183CA"
      sst: 1
      sd: "000001"
      dnn: internet
      amf: "8000"
      qos_index: 9
    - imsi: "001010000000002"
      key: "465B5CE8B199B49FAA5F0A2EE238A6BC"
      opc: "E8ED289DEBA952E4283B54E88E6183CA"
      sst: 2
      sd: "000002"
      dnn: streaming
      amf: "8000"
      qos_index: 9
    - imsi: "001010000060592"
      key: "1B9DC14B6E16A8FE83AA0E8A0AB56FCB"
      opc: "8CD505786285C50FEC35AD9D328816EA"
      sst: 1
      sd: "000001"
      dnn: internet
      amf: "8000"
      qos_index: 9
    - imsi: "001010000060594"
      key: "6526B07605B6D5663FD947C5BA65D141"
      opc: "FA25065FAC14E0EB5196BAD382B72C09"
      sst: 2
      sd: "000002"
      dnn: streaming
      amf: "8000"
      qos_index: 9
    - imsi: "001010000060597"
      key: "E8CD15760B3C91F85E750E66EC6688EC"
      opc: "86BA674F840472143F0B06B070F42234"
      sst: 1
      sd: "000001"
      dnn: internet
      amf: "8000"
      qos_index: 9
    - imsi: "001010000060599"
      key: "2F6E0B8F5C329503497A816D813FCB5C"
      opc: "85DCACDF39894DAA5D8A6BD18A44EB7D"
      sst: 2
      sd: "000002"
      dnn: streaming
      amf: "8000"
      qos_index: 9
